object_geometries:
  scatola    : {box: [0.05, 0.05, 0.05], color: [1,0.0,0.0,1]}
  box    : {box: [0.15, 0.05, 0.05], color: [0.75,0.75,0.75,1]}
  big_box_cartesian : {box: [0.2, 0.2, 0.3], color: [0.5,0.5,0.5,1]}
  big_box_sharework: {box: [0.3, 0.3, 0.3], color: [1,0.0,0.0,1]}
