scene_objects:
  - {type: "scatola", frame: "world", position: [0.5,0.5,0.2], quaternion: [0, 0, 0, 1]}
  - {type: "scatola", frame: "world", position: [1,0.5,0.2], quaternion: [0, 0, 0, 1]}
  - {type: "big_box_cartesian", frame: "world", position: [0.7,0.5,0.2], quaternion: [0, 0, 0, 1]}

# - {type: "big_box_cartesian", frame: "world", position: [0.5,0.5,0.2], quaternion: [0, 0, 0, 1]}
# - {type: "big_box_cartesian", frame: "world", position: [0.5,0.5,0.2], quaternion: [1, 0, 0, 1]}
# - {type: "big_box_cartesian", frame: "world", position: [0.5,0.5,0.2], quaternion: [0, 1, 0, 1]}
